### ISSUE TITLE
ARM6 and ARM7 NodeJs and npm

### ISSUE THREAD

**Issue by audstanley** [trasukg/share-tnc#1]
I love some of the projects you have created in npm!  I'm in the process of getting my ham radio license, and I already have a TNCPi2 kit that I've soldered together, attached to a Baofeng, and am currently (at the moment) monitoring APRS packets.  I'm extremely interested in experimenting with the code you've provided (share-tnc), and look forward to understanding more on sockets.

I noticed that your README.md  shows how you can install the latest NodeJs for a raspberry pi on an ARM6, and I put together a github repository for installing the latest version of NodeJs on **either** an ARM6 or ARM7 type raspberry pi.  This alleviates the user from having to figure out which version processor they have, where to put the symlinks, and if they want to update to an even new version of Node, they can re-run the script, and it will re-install node, and npm to the latest version.

Here is the source code:
https://github.com/audstanley/NodeJs-Raspberry-Pi

So if you want to add the block of code to your README.md under the [raspberry pi](https://github.com/trasukg/share-tnc#side-note-installing-nodejs-on-the-raspberry-pi) section then visitors can find a fresh install of Node and npm without worrying about which version of processor they have. The code block would look like this:

```sh
cd;
git clone https://github.com/audstanley/NodeJs-Raspberry-Pi;
cd NodeJs-Raspberry-Pi;
chmod +x Install-Node.sh;
sudo ./Install-Node.sh;
cd .. && rm -R -f NodeJs-Raspberry-Pi/;
node -v;
```

👍 Thank you for your code!
- Richard Stanley

**Comment by trasukg** [comment]
Hi Richard:

Thanks for the kind words.

I’d be happy to link to your script… however…  I didn’t try your script, so perhaps you do something different, but I did try to load the ARM-V7l version of Node onto a Pi 2 Model B, which responds to ‘uname -m’ with ‘armv7l’, and I got an “Illegal instruction” error when I tried to run node.  The leads me to think that the armv7 version of Node isn’t happy with Raspbian, which is apparently compiled for armv6.  Any thoughts?

Cheers,

Greg Trasuk

**Comment by audstanley** [comment]
I've used the script on a Raspberry Pi 2 recently (i'm pretty sure, like in the last few weeks), and didn't have any issues. I don't bother with whatever versions of NodeJs come on the Pi as a Rasbian release. I believe that is version 0.10.something which is *way* too old in my opinion.  There has been so many updates to NodeJs (native promises in and deep arrow functions in particular) which are a huge step forward for Node applications. 

The script also doesn't doing **any** compiling, it curl requests the distribution page and simply uses uname -m >> into the curl request.  The script assumes that NodeJs' distro page is releasing a properly compiled version of node and npm for the architecture (which is safe to assume, more so than whatever version is being released with Raspbian it sounds like).

After receiving the distribution, makes multiple symbolic links.  I am going to eventually update the script to warn users if symbolic links *already* exist, since one could use the same code block to update to the latest version of Node.  The downside is that the previous version of node is removed, and any global packages are removed also (which **can** be a good thing).  The script was made for a fresh install of node and npm, not exactly for updates, (though it **can** be used for that).  

Maybe in the next few days I'll upload a youtube video of nodeJs on a fresh install of Raspbian on a raspberry pi 2, and post the video.  

Happy Hamming,

- Richard Stanley

**Comment by trasukg** [comment]
Next time I have to install node, I'll try out your script again.
