### ISSUE TITLE
"KISS Noise" when connecting BPQ32 <-> Direwolf 1.5 via share-tnc

### ISSUE THREAD

**Issue by radar27** [trasukg/share-tnc#3]
Greetings,

When inserting share-tnc in between BPQ32 and Direwolf (all TCPKISS), the following errors appear  on the Direwolf console:

---

```
>>>

 Fake command prompt to KISS client application, total length = 6
  000:  0d 0a 63 6d 64 3a                                ..cmd:

<<< Rejected Noise from KISS client application, total length = 6
  000:  0a 63 6d 64 3a 0d                                .cmd:.
KISS TCP: Something unexpected from client application.
Is client app treating this like an old TNC with command mode?
This can be caused by the application sending commands to put a
traditional TNC into KISS mode.  It is usually a harmless warning.
For best results, configure for a KISS-only TNC to avoid this.
In the case of APRSISCE/32, use "Simply(KISS)" rather than "KISS."

>>> Fake command prompt to KISS client application, total length = 6
  000:  0d 0a 63 6d 64 3a                                ..cmd:
```

---

The actual share-tnc command is:

`share-tnc 192.168.1.100:8001 12345 --baud=1200`

This error appears after BPQ32 connects, but this error does not appear when BPQ32 goes directly to Direwolf.  

As best I can tell, these errors are surfacing when the client application is trying to set timing parameters on the KISS TNC itself, such as:

PERSIST
SLOTTIME
TXDELAY
AXHANG/TXTAIL

I have done some testing with other clients, including XRouter32 (via com0com) and native Linuxnode (kissattach via socat).  It appears to be present across all of them.

Setup a KISS port in /etc/ax25/axports
```
1       MYCALL          1200    255     2       Share TNC
```

This opens up a psuedo device that kissattach can then connect to (add & to send to the background)

`socat -d -d -d PTY,raw,echo=0,link=/tmp/kisstnc TCP4:127.0.0.1                                                                             :12345,reuseaddr`

This performs the actual kissattach.  For some reason going directly to /tmp/kisstnc gets a permission denied despite the symlink being 777 and kissattach running as root, but going to it's symlink target is ok.  The nested command grabs the symlink target (/tmp/kisstnc -> /dev/pts/3 in this example)

`sudo kissattach $(ls -l /tmp/kisstnc | tr ' ' '\n' | tail -n1) 1 44.128.0.1`

At this point Linux has an interface ready on ax0 (or higher if something already exists).  Watching the Direwolf console and setting kissparms via Linux console will produce the errors:

```
sudo kissparms 1 -p 192
sudo kissparms 1 -s 64
sudo kissparms 1 -l 30
```

The actual handling of AX.25 frames seems to work well, but something pertaining to exchanging KISS parameters between the client (BPQ32, XRouter32, LinuxNode) and server (Direwolf) is getting mangled in such a way that Direwolf is reporting invalid data.

Would it be possible to review the various KISS timing parameters and see if share-tnc can be updated to pass them through from client to server?

Thanks & 73

**Comment by trasukg** [comment]
You'll have to excuse me, I'm not familiar with BPQ32.  When you're seeing the error in DireWolf, are you connecting BPQ32 directly to share-tnc using Kiss-over-TCP, or are you using the "socat" trick?

Hard to say what's going on.  share-tnc should pass the KISS frames unmodified.  I will say that I'm pretty sure that DireWolf wants to have the timing parameters set in its config file, and is probably ignoring any settings it receives over KISS.  Perhaps you could try setting the KISSOPTIONS=NOPARAMS option on your PORT configuration in BPQ32.

If you really do want to look deeper, we'd probably have to write some custom diagnostics.  If you're transferring packets OK once connected, I'd say just ignore the error :-)

**Comment by radar27** [comment]
Yes I'll be glad to run a custom diagnostic/debug version.  BPQ32 is just one of the client systems that seems to produce it (Xrouter32 on Windows using com0com to gain TCP KISS connectivity as well as Linuxnode with socat) also seem to run into the same issue.  In the case of BPQ32 I was using it's native TCP KISS support:

BPQ32 -> share-tnc -> Direwolf

When I attach BPQ32 directly to Direwolf, (TCP KISS) the KISS parameters are passed and register what I think is correctly.  I get this back from the Direwolf console:
```

KISS protocol set TXDELAY = 35 (*10mS units = 350 mS), port 0
KISS protocol set Persistence = 64, port 0
KISS protocol set SlotTime = 10 (*10mS units = 100 mS), port 0
KISS protocol set TXtail = 3 (*10mS units = 30 mS), port 0
KISS protocol set FullDuplex = 0, port 0

```

I could be wrong, but as I understand it the KISS frames that carry actual AX.25 are not what is being sent here, from what I can find they are considered "command codes"

https://en.wikipedia.org/wiki/KISS_(TNC)#Command_codes

I am not quite sure how to send these via something like telnet, but if you do telnet to a direwolf TCP KISS listener and hit enter it will return a "cmd:" prompt.  This will also generate the "Rejected noise from KISS client" error in Direwolf:

```

$ telnet 192.168.1.100:8001
Trying 192.168.1.100...
Connected to 192.168.1.100.
Escape character is '^]'.


cmd:

```

From what I can gather from http://www.ax25.net/kiss.aspx (section 4 paragraph 2), there is a type indicator at the beginning.  Purely guessing as to what is happening, but think the indicator may always be set at 0 (data frame) even if the function following it is a command code, probably looking like a broken data frame having timing parameters instead of a standard source/destination callsigns, etc. 

Hopefully this helps, I'll be happy to run a special version to continue debugging as well.  Also please be aware that there is a debug option within Direwolf if that helps in troubleshooting KISS network client data.  When launching direwolf, just include the "-dn" switch.

I appreciate the help!

**Comment by trasukg** [comment]
There was a bug in utils-for-aprs that would cause a framing error that I believe was responsible for this bug.  Please update to the latest version of share-tnc and try it out.
