### ISSUE TITLE
Compatibility with Kenwood TH-D75 KISS TNC

### ISSUE THREAD

**Issue by xinugrk** [trasukg/share-tnc#8]
I attempted to share a TH-D75 in KISS mode QtTermTCP on a Raspberry Pi 5 running BookWorm.

Share-tnc reports the connection from QtTermTCP but no interaction with the TNC.

QtTermTCP works when connected directly to the serial port.

Is there something missing in the connection protocol? Not sure what TCP-to-TNC is about.

Is there a verbose mode to show the packets between connections.

Thanks,

Greg

**Comment by trasukg** [comment]
HI Greg:

Any chance you could screenshot the output that you see when you start up share-tnc?  You should see something similar to this:



In particular, if you don’t see the line “Connected to TNC…” then there may be something wrong with the connection.

Greg.

**Comment by trasukg** [comment]
(Looks like screenshots don’t work, so same message repeated with text)

Any chance you could screenshot the output that you see when you start up share-tnc?  You should see something similar to this:
***@***.***:~/devel/utils-for-aprs $ share-tnc --baud=1200 /dev/ttyUSB0 8001
{
  _: [],
  baud: 1200,
  '$0': 'share-tnc',
  path: '/dev/ttyUSB0',
  port: 8001
}
Connected to TNC on /dev/ttyUSB0 at 1200 baud.
TCP Endpoint received a connection from 192.168.1.101:60858

In particular, if you don’t see the line “Connected to TNC…” then there may be something wrong with the connection.

Greg.

**Comment by xinugrk** [comment]
Hi Greg:

Thanks for the quick reply on this.
Sorry, I jumped the gun on this one.
I tried it this morning as shown below and it WORKED beautifully!
Connected and tested from QtTermTCP on the host RPI & LAN RPI and Windoze Winlink Express over LAN.
I really need to sleep on it and try again before reporting an issue.

Thanks for the assistance,

Greg VE3ECI

➜  ~ share-tnc --version
1.0.8
➜  ~ 

➜  ~ share-tnc /dev/ttyACM0 8001 --baud 9600
{
  _: [],
  baud: 9600,
  '$0': 'share-tnc',
  path: '/dev/ttyACM0',
  port: 8001
}
Connected to TNC on /dev/ttyACM0 at 9600 baud.
TCP Endpoint received a connection from 192.168.2.75:46162
TCP connection from 192.168.2.75:46162 was closed
TCP Endpoint received a connection from 192.168.2.173:64796
Got socket closed event.
TCP Endpoint received a connection from 192.168.2.66:39776
TCP connection from 192.168.2.173:64796 was closed

**Comment by trasukg** [comment]
Awesome!  Never tried BPQ32 myself, but share-tnc processes at the AX.25 packet level, so it should work just fine.  You should be able to operate a node and also attach a client to the same radio now (although on my quick read that functionality may already be built into the BPQ32 node software).

**Comment by xinugrk** [comment]
FYI…

BPQ32 looks interesting but hasn’t been updated since 2016 and is remains ARM32 object.
